language: python

python:
  - "3.4"
env:
  global:
    - DJANGO_SETTINGS_MODULE="footbag_site.settings"
    - PYTHONPATH="/home/travis/build/shuttle1987/footbag-db"
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO=1.7 DB=mysql

#commands to install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -q -r requirements.txt

#command to run the test suite
script:
  - python manage.py test
